# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-12 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0014_auto_20180413_1959'),
        ('pinax_stripe', '0008_auto_20190816_2218'),
    ]

    operations = [
    ]
